### PR TITLE
FIX: attribute convention ala sklearn

### PR DESCRIPTION
**Pull request by kingjr**
sklearn naming convention is to have init params given by the subject without a `_` at the end and attributes created by the method with a `_`.

e.g.
```
myclass = MyClass(foo=1)
myclass.foo
myclass.fit()
myclass.bar_
```

That's a lot of changes, some of which are backward incompatible, but I think it's generally safer to stick to their naming convention.

### CODE REVIEW

**Comment by alexandrebarachant** [comment]
wow, thats a lot of works :)

i agree, the toolbox is still young so we can do this kind of change, and it's better to stick to the sklearn conventions.

Can you check the examples, i think i access internal variables to plot things.

Don't worry for travis, it's related to #19

**Comment by kingjr** [comment]
Ok. I also removed the channel renaming in the examples, because mne-python doesn't allow manual renaming manually anymore https://github.com/mne-tools/mne-python/pull/1124

**Comment by alexandrebarachant** [comment]
So far, i'm happy with this PR. 

Perhaps we could add a "contribution guideline" in the Readme, stating the different conventions.

When your ready, update the What's new and i will merge.

Note that i plan to rewrite almost completly the stats functions in a near future (the code is old and too convoluted)

**Comment by kingjr** [comment]
Ok. I haven't looked at the way stats work yet. I've kept the contribution guidelines minimalistic 1) because I'm lazy) and 2) because they can become super overwhelming. Most packages actually refer to an external doc.

BTW, you may want to go through all files with flake8.

**Comment by alexandrebarachant** [comment]
Thanks.

File i edited recently are supposed to be Flake8 verified and properly documented.
There are only a few files where i did not finished it: stats.py and estimation.py + some of the examples.
This is actually one of my milestone to release a new major version (see #1)

**Comment by kingjr** [comment]
all right thanks!

**Pull request merged**
