### PR TITLE
FIX: doc utils.covariance

### PR DESCRIPTION
**Pull request by kingjr**
Typos in docs

### CODE REVIEW

**Comment by alexandrebarachant** [comment]
Thanks,
the online doc will be updated with the next release

**Comment by kingjr** [comment]
Wait you've been too fast, I found some more ;)

**Comment by kingjr** [comment]
https://github.com/kingjr/pyRiemann/commit/3c5e21df80c78ca36db5dee16b83151318b82989

**Comment by alexandrebarachant** [comment]
okay, i will wait a bit .... My english is terrible :)

**Comment by kingjr** [comment]
The branch is merged already, I suggest you cherry pick the last commit.

**Pull request merged**
