### PR TITLE
ENH: handle flat channels in Xdawn

### PR DESCRIPTION
**Pull request by kingjr**
Xdawn generates empty filters if there s a bad channels:

```
import numpy as np
from pyriemann.spatialfilters import Xdawn
X = np.random.rand(100, 30, 20)
y = np.random.randint(0, 2, 100)
X[:, 20:, :] = 0
Xdawn(estimator='oas').fit_transform(X, y)
```

This fixes it

(I also added some tests to the baseline covariance)

### CODE REVIEW

**Comment by kingjr** [comment]
I'm not sure whether `picks` should be stored publicly, probably a private attribute should be better

**Comment by alexandrebarachant** [comment]
Hum,
Would it be preferable to drop the bad channels before feeding the data to xDawn ?

**Comment by alexandrebarachant** [comment]
Hi again,
I appreciate the contrib, and generally speaking we will face similar problem for any other method. 

Flat channels creates rank-deficient mat-cov, and despite the regularization it leads to error in the joint diagonalization.

I would suggest you refactor this in a `FlatChannelDetector` transformer (or something with a better name) so that it can be pipelined before any other method.

WDYT ?

**Comment by kingjr** [comment]
yes, definitely a better idea. I'll close this PR, and open a new one to keep it clean.

**Pull request closed without merging**
