### PR TITLE
FIX: decommented imports in __init__.py to make README example work

### PR DESCRIPTION
**Pull request by emanuele**
Currently, the example in the README file does not work because imports fail, due to issues in `pyriemann/__init__.py`. This little PR fixes that.

### CODE REVIEW

**Comment by kingjr** [comment]
LGTM

**Comment by alexandrebarachant** [comment]
looks like travis with python 3 raise some import error.

i think we should do some relative import.

can you add clustering too

**Comment by emanuele** [comment]
OK for importing clustering (stats too?).
Unfortunately I cannot directly test for Python 3 on my laptop at the moment. Will try to dig into that tomorrow.

**Comment by alexandrebarachant** [comment]
you can import stats too, it will be cleaner once i merged #37 

i think you need to do relative import, ie : 

```python
from . import classification
```

**Comment by emanuele** [comment]
Thanks for the suggestion and sorry for the latency. I'm on holidays these days :) but couldn't spent time on this one :(. Will do now.

**Comment by alexandrebarachant** [comment]
no problem, take your time.
the example on the readme is a bit outdated, you can check here for working examples : http://pythonhosted.org/pyriemann/index.html

i'm planning some tutorial too (see #33 ), i hope it will be ready for the next release

**Comment by alexandrebarachant** [comment]
Okay, all good. 
thanks

**Comment by emanuele** [comment]
Thanks to you for pyRiemann!!

**Pull request merged**
